apiVersion: aws.platform.upbound.io/v1alpha1
kind: XIRSA
metadata:
  name: configuration-aws-eks-irsa-capi
spec:
  parameters:
    id: configuration-aws-eks-irsa-capi
    condition: StringEquals
    policyDocument: |
      {
          "Version": "2012-10-17",
          "Statement": [
              {
                  "Action": [
                      "kms:Decrypt",
                      "kms:DescribeKey"
                  ],
                  "Effect": "Allow",
                  "Resource": "*"
              }
          ]
      }
    serviceAccount:
      name: kustomize-controller
      namespace: flux-system